### ISSUE TITLE
Remove the need of counting lines of code

### ISSUE THREAD

**Issue by icasrod** [etsiiull/SIMDE#10]
The first (no comment) line of a SIMDE code contains the number of instructions of the code itself. To avoid errors, it would be better to remove this line and automatically calculate the number of instructions without the intervention of the user.

**Comment by adrianabreu** [comment]
Shall we keep retrocompatibility making it optional or just remove the need of adding it?

**Comment by icasrod** [comment]
I think it's not difficult at all to keep it optional (you only need to ignore the first line if it's a number), so I would do it.

**Comment by adrianabreu** [comment]
I think that this is the safe approach:
If a number is found as first operand, we consider it the number of lines.
If not we try to calculate the number of lines.

I applied the followting treatment for build it.
From the given input, remove the lines that have commentaries inside. 
Trim each line and remove it if its length its zero.
Remove lines that contain any character following ':', that should be the labels lines.

I hope this works. Anyway if this fails it can be fixed by specifying the number of lines at the beginning.
